webtalk_init -webtalk_dir /home/rommac/vivado/projects/vhdl_learning/vhdl_learning.sim/sim_1/behav/xsim/xsim.dir/IIC_SIM_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun  1 02:51:56 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "00b3ff13-4c6f-4017-bcbf-49c08c9e0961" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0d91fe4178b64775bcd90cbaabebee31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3200.746 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "101 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.80_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124224_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2487391809 -regid "" -xml /home/rommac/vivado/projects/vhdl_learning/vhdl_learning.sim/sim_1/behav/xsim/xsim.dir/IIC_SIM_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/rommac/vivado/projects/vhdl_learning/vhdl_learning.sim/sim_1/behav/xsim/xsim.dir/IIC_SIM_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/rommac/vivado/projects/vhdl_learning/vhdl_learning.sim/sim_1/behav/xsim/xsim.dir/IIC_SIM_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
